from server import app
from server.view import healthz
from server.view.api import (
    access,
    action_target,
    ai_assignment,
    ai_ingest,
    ai_node,
    ai_settings,
    api_token,
    archive,
    audio_detection,
    auth,
    bookmark,
    camera,
    counting,
    dashboard,
    doorbell,
    detection,
    detection_zone,
    discovery,
    edge_recording,
    event,
    event_policy,
    export,
    external,
    face,
    federation,
    feature_flag,
    general_settings,
    live,
    lpr,
    share_link,
    monitor,
    notification,
    object_trigger,
    pairing,
    playback,
    portal,
    privacy_mask,
    ptz,
    recording,
    rule,
    schedule,
    semantic,
    site_map,
    snapshot,
    storage,
    subscription,
    talk,
    timelapse,
)
from server.view.api.admin import audit_log, permission, role, user

blueprint_list = [
    healthz.context,
    auth.context,
    user.context,
    role.context,
    permission.context,
    audit_log.context,
    # P1
    camera.context,
    discovery.context,
    ptz.context,
    snapshot.context,
    live.context,
    dashboard.context,
    # P2
    recording.context,
    playback.context,
    export.context,
    storage.context,
    # P3
    event.context,
    event_policy.context,
    schedule.context,
    timelapse.context,
    subscription.context,
    # P4
    detection.context,
    detection_zone.context,
    object_trigger.context,
    ai_node.context,
    ai_assignment.context,
    ai_settings.context,
    ai_ingest.context,
    # P5
    rule.context,
    action_target.context,
    monitor.context,
    pairing.context,
    notification.context,
    api_token.context,
    external.context,
    # P6
    feature_flag.context,
    bookmark.context,
    share_link.context,
    share_link.public_context,
    talk.context,
    semantic.context,
    privacy_mask.context,
    archive.context,
    site_map.context,
    counting.context,
    doorbell.context,
    edge_recording.context,
    audio_detection.context,
    lpr.context,
    face.context,
    federation.context,
    portal.context,
    access.context,
    general_settings.context,
]

for blueprint in blueprint_list:
    app.register_blueprint(blueprint)
